# Generated by Django 4.1.7 on 2023-03-02 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
        migrations.AddField(
            model_name='product',
            name='avaiable',
            field=models.BooleanField(default=False),
        ),
    ]
