# Generated by Django 4.1.7 on 2023-02-17 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_sample_price_alter_order_full_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactrequest',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
